<div class="sc-lightbox-container" style="display: none;">
    <div class="sc-lightbox-bg" onclick="close_Lightbox();"></div>
    <div class="sc-lightbox story_<?php echo $sk['lb_story']['id']; ?>">
        <div class="lb-container">
            <div class="img-float">
                <img src="<?php echo $sk['lb_story']['media'][0]['url']; ?>">

            </div>

            <div class="comment-flow">
                <div class="lb-story-meta">
                    <div class="lb-story-pubwrap">
                        <table border="0" width="100%">
                            <tr>
                                <td valign="top" align="left" width="55px">
                                    <img class="lb-story-pubavatar" src="<?php echo $sk['lb_story']['publisher']['thumbnail_url']; ?>" width="50px" alt="Avatar">
                                </td>

                                <td valign="top" align="left">
                                    <a class="lb-story-pubname" href="<?php echo $sk['lb_story']['publisher']['url']; ?>">
                                        <?php echo $sk['lb_story']['publisher']['name']; ?>
                                    </a>
                                    <br>
                                    <span class="lb-story-time ajax-time" title="<?php echo date('c', $sk['lb_story']['time']); ?>">
                                        <?php echo date('c', $sk['lb_story']['time']); ?>
                                    </span>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="lb-story-options">
                        <?php echo FA_getPostLikeButton($sk['lb_story']['id']); ?>
                        
                        <abbr class="space6">
                            &#183;
                        </abbr>
                        
                        <?php echo FA_getPostShareButton($sk['lb_story']['id']); ?>
                        
                        <abbr class="space6">
                            &#183;
                        </abbr>
                        
                        <?php echo FA_getPostFollowButton($sk['lb_story']['id']); ?>
                    </div>

                    <div class="lb-story-text">
                        <?php echo $sk['lb_story']['text']; ?>
                    </div>
                </div>

                <?php
                if ($sk['lb_story']['view_all_comments'] == true) {
                ?>
                <div class="view-more-wrapper" align="center" onclick="FA_loadAllComments(<?php echo $sk['lb_story']['id']; ?>);">
                    <i class="icon-lightbulb progress-icon hide"></i>
                    <?php
                    echo $lang['view_all_comments_label'];
                    ?>
                </div>
                <?php
                }
                ?>

                <div class="comments-wrapper">
                    <?php
                    foreach (FA_getComments($sk['lb_story']['id'], 8) as $sk['comment']) {
                        echo FA_getPage('lightbox/comment');
                    }
                    ?>
                </div>

                <div class="lb-comment-meta lb-new-comment-meta">
                    <table border="0" width="100%">
                        <tr>
                            <td valign="top" align="left" width="36px">
                                <img class="lb-comment-pubavatar" src="<?php echo $sk['user']['thumbnail_url']; ?>" width="32px" alt="Avatar">
                            </td>

                            <td class="lb-comment-textarea-wrapper" valign="top" align="left">
                                <textarea class="lb-new-comment-textarea auto-grow-input" placeholder="<?php echo $lang['comment_textarea_label']; ?>" onkeyup="FA_registerCommentviaLB(this.value,<?php echo $sk['lb_story']['id']; ?>,<?php echo $sk['user']['id']; ?>,event);"></textarea>
                                <i class="icon-lightbulb progress-icon hide"></i>
                            </td>
                        </tr>
                    </table>
                </div>

                <div class="lb-close-btn icon-remove" onclick="close_Lightbox();" title="Close"></div>
            </div>

            <div class="float-clear"></div>
        </div>
    </div>
    <?php
    list($width, $height) = getimagesize(str_replace($sk['config']['site_url'] . '/', '', $sk['lb_story']['media'][0]['url']));
    ?>
    <script>
    $(".lb-container").find(".img-float").find("img")
        .load(function() {
            $('.pre_load_wrap').remove();
            Adjust_Lightbox();
        });

    $(window).resize(function () {
        Adjust_Lightbox();
    });

    function Adjust_Lightbox() {
        $(".sc-lightbox-container").show();
        var sW = $(window).width();
        var sW_p80 = sW * 0.8;
        var sH = $(window).height();
        var SH_p10 = sH * 0.1;
        var Wi = <?php echo $width; ?>;
        var Hei = <?php echo $height; ?>;
        var LB_container = $(".sc-lightbox");
        var LB = $(".lb-container");
        var LB_imgwrap = LB.find(".img-float");
        var LB_img = LB_imgwrap.find("img");
        var LB_commentFlow = LB.find(".comment-flow");

        if (Wi > Hei) {
            var Hei_by_Wi = Hei / Wi;
            var maxWi = sW_p80;
            var LB_Hei = (maxWi - 350) * Hei_by_Wi;
            LB_containerMargin = ((sW - LB_Hei) / 2) - 4;

            LB.css("max-width", maxWi + 'px'); 
            LB_imgwrap.css("width", (maxWi - 350) + 'px');
            LB_img.css("width", "100%");
            LB_commentFlow.css("height", LB_Hei + 'px');

            var LBmargin = (sH - LB_imgwrap.find("img").height()) / 2;

            LB.css({
                "margin-top": LBmargin + 'px',
            });
        } else {
            var Wi_by_Hei = Wi / Hei;
            var SH_p80 = sH * 0.8;
            var maxWi = (SH_p80 * Wi_by_Hei) + 351;
            LB_containerMargin = ((sW - maxWi) / 2) - 4;

            LB.css("max-width", maxWi + 'px');
            LB_img.css("height", SH_p80 + 'px');
            LB_commentFlow.css("height", SH_p80 + 'px');

            var LBmargin = (sH - LB_imgwrap.find("img").height()) / 2;

            LB.css({
                "margin-top": LBmargin + 'px',
            });

            LB_container.css({
                left: LB_containerMargin + 'px',
                right: LB_containerMargin + 'px'
            });
        }
    }

    function close_Lightbox() {
        $(".sc-lightbox-container").remove();
    }

    function FA_registerCommentviaLB(text, post_id, timeline_id, event) {
        if (event.keyCode == 13 && event.shiftKey == 0) {
            main_wrapper = $('.story_' + post_id);
            comment_textarea = main_wrapper.find('.lb-comment-textarea-wrapper');
            textarea_wrapper = comment_textarea.find('textarea');
            textarea_wrapper.val('');
            
            FA_progressIconLoader(comment_textarea);
            
            $.post(FA_source() + '?t=post&a=comment&lb=1&post_id=' + post_id, {text: text, timeline_id: timeline_id}, function (data) {
                
                if (data.status == 200) {
                    main_wrapper.find('.comments-wrapper').append(data.html);
                    main_wrapper.find('.story-comment-activity').html(data.activity_html);
                }
                
                FA_progressIconLoader(comment_textarea);
            });
        }
    }
    </script>
</div>