<div class="page-margin"></div>
<div class="float-left span25">
    <div class="list-wrapper">
        <div class="list-header">
            <?php
            echo $lang['menu_label'];
            ?>
        </div>
        
        <a class="list-column" href="<?php echo SK_smoothLink('index.php?tab1=terms&tab2=tos'); ?>" data-href="?tab1=terms&tab2=tos">
            <?php
            echo $lang['terms_tos_label'];
            ?>
        </a>
        
        <a class="list-column" href="<?php echo SK_smoothLink('index.php?tab1=terms&tab2=privacy'); ?>" data-href="?tab1=terms&tab2=privacy">
            <?php
            echo $lang['terms_privacy_label'];
            ?>
        </a>
        
        <a class="list-column" href="<?php echo SK_smoothLink('index.php?tab1=terms&tab2=disclaimer'); ?>" data-href="?tab1=terms&tab2=disclaimer">
            <?php
            echo $lang['terms_disclaimer_label'];
            ?>
        </a>
        
        <a class="list-column" href="<?php echo SK_smoothLink('index.php?tab1=terms&tab2=contact'); ?>" data-href="?tab1=terms&tab2=contact">
            <?php
            echo $lang['terms_contact_label'];
            ?>
        </a>
        
        <a class="list-column" href="<?php echo SK_smoothLink('index.php?tab1=terms&tab2=about'); ?>" data-href="?tab1=terms&tab2=about">
            <?php
            echo $lang['terms_about_label'];
            ?>
        </a>
    </div>
</div>

<div class="float-right span74">
    <?php
    $term_type = null;
    
    if (isset($_GET['tab2'])) {
        $term_type = $_GET['tab2'];
    }
    
    switch($term_type) {
        case 'privacy':
            echo SK_getPage('terms/privacy');
        break;
        
        case 'disclaimer':
            echo SK_getPage('terms/disclaimer');
        break;
        
        case 'contact':
            echo SK_getPage('terms/contact');
        break;
        
        case 'about':
            echo SK_getPage('terms/about');
        break;
        
        default:
            echo SK_getPage('terms/tos');
    }
    ?>
</div>

<div class="float-clear"></div>