<div class="page-margin"></div>
<div class="float-left span63">
    <div class="e-album-upload-container" align="center">
        <?php
        if ($sk['album']['timeline_id'] == $sk['user']['id']) {
        ?>
        <div class="left-side e-album-uploader" onclick="javascript:$('.e-album-fileinput').click();">
            <i class="icon-cloud-upload progress-icon"></i> 
            <span>Upload Photos</span>
        </div>

        <div class="right-side album-delete-btn" onclick="SK_deleteAlbumWindow(<?php echo $sk['album']['id']; ?>);">
            <i class="icon-remove progress-icon"></i> 
            Delete Album
        </div>

        <div class="float-clear"></div>
        <?php
        } else {
        ?>
        <a class="full-width" href="<?php echo $sk['config']['site_url']; ?>/album/create" data-href="?tab1=album&tab2=create">
            <i class="icon-plus"></i> 
            Create Album
        </a>
        <?php
        }
        ?>
    </div>

    <div class="e-album-photos-container">
        <div class="album-name-header" align="center">
            <?php echo $sk['album']['name']; ?>
        </div>

        <p class="album-descr-para" align="center">
            <?php echo $sk['album']['descr']; ?>
        </p>

        <div class="album-photos">
            <?php
            foreach (SK_getAlbumPhotos($sk['album']['id']) as $photo) {
            ?>
            <div class="e-photo photo_<?php echo $photo['post_id']; ?>">
                <img src="<?php echo $sk['config']['site_url'] . '/' . $photo['url'] . '_100x100.' . $photo['extension']; ?>" width="100%" onclick="javascript:SK_openLightbox(<?php echo $photo['post_id']; ?>);">
                <?php
                if ($sk['album']['timeline_id'] == $sk['user']['id']) {
                ?>
                <div class="remove-btn" title="Delete Photo" onclick="SK_deletePostWindow(<?php echo $photo['post_id']; ?>);">
                    <i class="icon-remove"></i>
                </div>
                <?php
                }
                ?>
            </div>
            <?php
            }
            ?>
            <div class="float-clear"></div>
        </div>
    </div>
</div>

<div class="float-right span35">
    <div class="list-wrapper suggestions-wrapper">
        <div class="list-header">
            <div class="float-left">
                <?php
                echo $lang['follow_suggestions_label'];
                ?>
            </div>
            
            <div class="float-right">
                <span class="cursor-hand" onclick="refreshFollowSuggestions();" title="<?php echo $lang['refresh_label']; ?>">
                    <i class="icon-repeat progress-icon"></i> 
                    <?php
                    echo $lang['refresh_label'];
                    ?>
                </span>
            </div>
            
            <div class="float-clear"></div>
        </div>
        
        <div class="suggestions-content">
            <?php
            foreach (SK_getFollowSuggestions() as $sk['suggestion']) {
                echo SK_getPage('home/suggestion-wrap');
            }
            ?>
        </div>
    </div>
    
    <div class="list-wrapper trending-wrapper">
        <div class="list-header">
            <?php echo $lang['trending_header_label']; ?>
        </div>
        <div class="trending-content">
            <?php
            $trendings = SK_getTrendings('popular');
            
            if (is_array($trendings) && count($trendings) > 0) {
                
                foreach ($trendings as $sk['trend']) {
                    echo SK_getPage('hashtag/trend-wrap');
                }
            }
            ?>
        </div>
    </div>
    
    <?php
    echo $sk['config']['ad_place_timeline'];
    ?>
</div>

<div class="float-clear"></div>

<form class="e-album-form hidden" method="post" enctype="multipart/form-data">
    <input class="e-album-fileinput" type="file" name="photos[]" multiple="yes" onchange="javascript:$('.e-album-form').submit();">
    <input type="hidden" name="album_id" value="<?php echo $sk['album']['id']; ?>">
</form>

<script>
$(function () {
    $('form.e-album-form').ajaxForm({
        url: SK_source() + '?t=album&a=upload',
        
        beforeSend: function() {
            SK_progressIconLoader($('.e-album-uploader'));
        },

        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            var container = $('.e-album-uploader');
            container.find('span').text('<?php echo $lang['uploading']; ?>... ' + percentVal);

            if (percentComplete == 100) {
                container.find('span').text('<?php echo $lang['please_wait']; ?>...');
            }
        },
        
        success: function(responseText) {
            var container = $('.e-album-uploader');

            if (responseText.status == 200) {
                $('.album-photos').prepend(responseText.html);
            }

            SK_progressIconLoader(container);
            container.find('span').text('Upload Photos');
        }
    });
});

function SK_deleteAlbumWindow(album_id) {
    button_wrapper = $('.album-delete-btn');
    SK_progressIconLoader(button_wrapper);

    $.get(SK_source(), {t: 'album', album_id: album_id, a: 'delete_window'}, function(data) {
        
        if (data.status == 200) {
            $(document.body)
                .append(data.html)
                .css('overflow','hidden');
            
            if ($('.header-wrapper').width() < 920) {
                $('.window-wrapper').css('margin-top',($(document).scrollTop()+10)+'px');
            }
        }
        
        SK_progressIconLoader(button_wrapper);
    });
}

function SK_deleteAlbum(album_id) {
    SK_closeWindow();
    $.get(SK_source(), {t: 'album', album_id: album_id, a: 'delete'}, function(data) {
        
        if (data.status == 200) {
            window.location = data.location;
        }
    });
}
</script>