<div class="page-margin"></div>

<div class="float-left span63">
	<form class="s-album-container" method="post" enctype="multipart/form-data">
		<div class="s-album-header">
			Create an album
		</div>

		<div class="album-field-wrap">
			<div class="album-label">Name:</div>
			<input type="text" name="album_name" placeholder="Name of album">
		</div>

		<div class="album-field-wrap">
			<div class="album-label">Description:</div>
			<textarea name="album_descr" placeholder="Description"></textarea>
		</div>

		<div class="album-field-wrap">
			<div class="album-label">Upload Photos:</div>
			<input type="file" name="photos[]" multiple>
		</div>

		<div class="album-field-wrap">
			<button class="active" name="album_btn">Create Album</button>
		</div>
	</form>

	<div class="page-margin"></div>
</div>

<div class="float-right span35">
	<div class="list-wrapper suggestions-wrapper">
        <div class="list-header">
            <div class="float-left">
                <?php
                echo $lang['follow_suggestions_label'];
                ?>
            </div>
            
            <div class="float-right">
                <span class="cursor-hand" onclick="refreshFollowSuggestions();" title="<?php echo $lang['refresh_label']; ?>">
                    <i class="icon-repeat progress-icon"></i> 
                    <?php
                    echo $lang['refresh_label'];
                    ?>
                </span>
            </div>
            
            <div class="float-clear"></div>
        </div>
        
        <div class="suggestions-content">
            <?php
            foreach (FA_getFollowSuggestions() as $sk['suggestion']) {
                echo FA_getPage('home/suggestion-wrap');
            }
            ?>
        </div>
    </div>
    
    <div class="list-wrapper trending-wrapper">
        <div class="list-header">
            <?php echo $lang['trending_header_label']; ?>
        </div>
        <div class="trending-content">
            <?php
            $trendings = FA_getTrendings('popular');
            
            if (is_array($trendings) && count($trendings) > 0) {
                
                foreach ($trendings as $sk['trend']) {
                    echo FA_getPage('hashtag/trend-wrap');
                }
            }
            ?>
        </div>
    </div>
    
    <?php
    echo $sk['config']['ad_place_timeline'];
    ?>
</div>

<div class="float-clear"></div>
<script>
$(function () {
    $('form.s-album-container').ajaxForm({
        url: FA_source() + '?t=album&a=create',
        
        beforeSend: function() {
            var formButton = $('form.s-album-container').find('button');
            formButton.removeClass('active').text('<?php echo $lang['creating']; ?>...').css('disabled', true);
        },

        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            var formButton = $('form.s-album-container').find('button');

            formButton.removeClass('active').text('<?php echo $lang['creating']; ?>... ' + percentVal).css('disabled', true);

            if (percentComplete == 100) {
                formButton.removeClass('active').text('<?php echo $lang['please_wait']; ?>...').css('disabled', true);
            }
        },
        
        success: function(responseText) {
            var formButton = $('form.s-album-container').find('button');

            if (responseText.status == 200) {
                window.location = responseText.url;
            } else {
                formButton.addClass('active').text('<?php echo $lang['album_create_label']; ?>').css('disabled', false);
            }
        }
    });
});
</script>