Hey <?php echo $sk['mail']['name']; ?>, how are you? Thanks for joining <?php echo $sk['config']['site_name']; ?>.
<br><br>
Please verify your email by clicking this link:
<br>
<a href="<?php echo $sk['mail']['verification_link']; ?>"><?php echo $sk['mail']['verification_link']; ?></a>
<br><br>
See you at <?php echo $sk['config']['site_name']; ?>, have a good day. :)
<br><br>
Sincerely,
<br>
<?php echo $sk['config']['site_name']; ?>