Hey <?php echo $sk['mail']['name']; ?>, how's it going? We already miss you at <?php echo $sk['config']['site_name']; ?> :(
<br><br>
Did you forget your password by any chance? It seems like you did. No worries though, we got it covered! ;)
<br><br>
You can click the following link to reset your password: <a href="<?php echo $sk['mail']['url']; ?>"><?php echo $sk['mail']['url']; ?></a>
<br><br>
You will be asked to enter a new password. It is recommended that you choose a password that is strong, contains alphanumeric and special characters. It's best if you don't use the same password you are using on other sites. Keep it unique and shhhh... don't tell it to anyone.. :P
<br><br>
By the way, if you did not request to reset your password, no need to panic, just ignore this e-mail.
<br><br>
See you at <?php echo $sk['config']['site_name']; ?>, have a good day. :)
<br><br>
Sincerely and lovingly,
<br>
<?php echo $sk['config']['site_name']; ?>