<div class="header-wrapper" name="top">
    <div class="header-content">
        <div class="float-left">
            <table border="0" cellspacing="0" cellpadding="0">
            <tr>
                <td class="header-site-logo" align="left" valign="top">
                    <a href="<?php echo $sk['config']['site_url']; ?>" style="margin-left: 10px;">
                        <img src="<?php echo $sk['config']['theme_url']; ?>/logo.png" alt="<?php echo $sk['config']['site_name']; ?>">
                    </a>
                </td>
                <td align="left" valign="top">
                    <div class="header-live-search">
                        <input value="<?php echo $lang['header_search_textarea_label']; ?>" placeholder="<?php echo $lang['header_search_textarea_label']; ?>" data-placeholder="<?php echo $lang['header_search_textarea_label']; ?>" type="text" onkeyup="FA_headerSearch(this.value);">
                    </div>
                </td>
            </tr>
            </table>
        </div>
        <div class="float-right">
            <?php
            if ($sk['logged'] == true) {
            ?>
            <a class="header-nav float-left" href="<?php echo FA_smoothLink('index.php?tab1=home'); ?>" title="<?php echo $lang['home_label']; ?>" data-href="?tab1=home">
                <i class="icon icon-home"></i>
            </a>
            <a class="notification-nav header-nav float-left" title="<?php echo $lang['notification_label']; ?>" onclick="FA_openNotifications();">
                <i class="icon icon-globe"></i>
                <?php
                $notification_alert = FA_countNotifications(
                    array(
                        'unread' => true
                    )
                );
                $hidden_class = '';
                
                if ($notification_alert == 0) {
                    $hidden_class = ' hidden';
                }
                ?>
                <span class="new-update-alert<?php echo $hidden_class; ?>">
                    <?php echo $notification_alert; ?>
                </span>
            </a>
            <a class="message-nav header-nav float-left" href="<?php echo FA_smoothLink('index.php?tab1=messages'); ?>" title="<?php echo $lang['message_label']; ?>" data-href="?tab1=messages">
                <i class="icon icon-comments"></i>
                <?php
                $message_alert = FA_countMessages(
                    array(
                        'new' => true,
                        'update' => false
                    )
                );
                $hidden_class = '';
                
                if ($message_alert == 0) {
                    $hidden_class = ' hidden';
                }
                ?>
                <span class="new-update-alert<?php echo $hidden_class; ?>">
                    <?php echo $message_alert; ?>
                </span>
            </a>
            <?php
            $new_follow_requests = FA_countFollowRequests();
            $hidden_class = '';
            $follow_nav_url = 'index.php?tab1=timeline&tab2=requests&id=' . $sk['user']['username'];
            
            if ($new_follow_requests == 0) {
                $hidden_class = ' hidden';
                $follow_nav_url = 'index.php?tab1=timeline&tab2=following&id=' . $sk['user']['username'];
            }

            if ($sk['config']['friends'] == true) {
                $follownavTitle = $lang['header_friends_label'];
            } else {
                $follownavTitle = $lang['header_following_label'];
            }
            ?>
            <a class="followers-nav header-nav float-left" href="<?php echo FA_smoothLink($follow_nav_url); ?>" title="<?php echo $follownavTitle; ?>" data-href="<?php echo str_replace('index.php', '', $follow_nav_url); ?>">
                <i class="icon icon-group"></i>
                <span class="new-update-alert<?php echo $hidden_class; ?>">
                    <?php
                    echo $new_follow_requests;
                    ?>
                </span>
            </a>
            <a class="manager-nav header-nav float-left" href="<?php echo FA_smoothLink('index.php?tab1=more'); ?>" title="<?php echo $lang['my_pages_groups_label']; ?>" data-href="?tab1=more">
                <i class="icon icon-reorder"></i>
            </a>
            <div class="header-user-info float-left cursor-hand" style="position: relative;">
                <a class="header-user-link" href="<?php echo $sk['user']['url']; ?>" data-href="?tab1=timeline&id=<?php echo $sk['user']['username']; ?>">
                    <img class="header-user-avatar" src="<?php echo $sk['user']['thumbnail_url']; ?>" width="24px" alt="<?php echo $sk['user']['name']; ?>">
                    <strong><?php echo $sk['user']['first_name']; ?></strong>
                </a>
                <i class="icon-caret-down dropdown-icon"></i>
                <span class="dropdown-overlay-wrap" onclick="FA_moreToggle();"></span>
            </div>
            <div class="float-clear"></div>
            <?php
            } else {
            ?>
            <a class="header-join-wrapper" href="<?php echo FA_smoothLink('index.php?tab1=welcome'); ?>" title="<?php echo $lang['header_join_label']; ?>">
                <i class="icon icon-signin"></i> <?php echo $lang['header_join_label']; ?>
            </a>
            <?php
            }
            ?>
        </div>
        <div class="float-clear"></div>
    </div>
</div>
<div class="dropdown-search-container">
    <div class="dropdown-search-wrapper">
        <div class="dropdown-search-content float-left">
            <div class="search-header">
                <i class="icon-search progress-icon hide"></i>
                <?php echo $lang['header_search_header_label']; ?>
            </div>
            
            <div class="search-list-wrapper"></div>
            
            <div align="center">
                <a class="page-link" href="#">
                    <?php echo $lang['header_search_all_results_label']; ?>
                </a>
            </div>
        </div>
        <div class="float-clear"></div>
    </div>
</div>
<?php
if ($sk['logged'] == true) {
?>
<div class="dropdown-notification-container">
    <div class="dropdown-notification-wrapper">
        <div class="dropdown-notification-content float-right">
            <div class="notification-header">
                <i class="icon-globe progress-icon hide"></i>
                <?php echo $lang['notification_header_label']; ?>
            </div>
            
            <div class="notification-list-wrapper"></div>
        </div>
        
        <div class="float-clear"></div>
    </div>
</div>
<div class="dropdown-more-container">
    <div class="dropdown-more-wrapper">
        <div class="dropdown-more-content float-right">
            <div class="more-header"><?php echo $lang['more_header_label']; ?></div>
            
            <div class="more-list-wrapper">
                <a class="more-list" href="<?php echo $sk['user']['url']; ?>" data-href="?tab1=timeline&id=<?php echo $sk['user']['username']; ?>">
                    <i class="icon icon-user"></i> <?php echo $lang['my_profile_label']; ?>
                </a>
                
                <a class="more-list" href="<?php echo FA_smoothLink('index.php?tab1=more'); ?>" data-href="?tab1=more">
                    <i class="icon icon-reorder"></i> <?php echo $lang['my_pages_groups_label']; ?>
                </a>
                
                <a class="more-list" href="<?php echo FA_smoothLink('index.php?tab1=settings'); ?>" data-href="?tab1=settings">
                    <i class="icon icon-gear"></i> <?php echo $lang['more_settings_label']; ?>
                </a>
                
                <a class="more-list" href="<?php echo FA_smoothLink('index.php?tab1=logout'); ?>">
                    <i class="icon icon-signout"></i> <?php echo $lang['logout']; ?>
                </a>
            </div>
        </div>
        
        <div class="float-clear"></div>
    </div>
</div>
<?php
}
?>
<script>
<?php
if ($sk['logged'] == true) {
?>
function FA_openNotifications() {
    $('.dropdown-search-container').hide();
    $('.dropdown-more-container').hide();
    notification_container = $('.dropdown-notification-container');
    notification_container.toggle();
    
    if (notification_container.css('display') == "block") {
        $('.notification-nav').addClass('header-nav-active');
        FA_progressIconLoader(notification_container.find('.notification-header'));
        
        $.get(FA_source(), {t: 'notifications'}, function (data) {
            
            if (data.status == 200) {
                
                if (data.html.length == 0) {
                    $('.notification-list-wrapper').html('<div class="no-wrapper" align="center"><?php echo $lang['no_notifications']; ?></div>');
                } else {
                    $('.notification-list-wrapper').html(data.html);
                    FA_intervalUpdates();
                }
            }
            
            FA_progressIconLoader(notification_container.find('.notification-header'));
        });
    } else {
        $('.notification-nav').removeClass('header-nav-active');
    }
}
<?php
}
?>
function FA_headerSearch(query) {
    $('.dropdown-more-container').hide();
    $('.dropdown-notification-container').hide();
    $('.notification-nav').removeClass('header-nav-active');
    search_wrapper = $('.dropdown-search-container');
    
    if (query.length == 0) {
        search_wrapper.hide();
    }
    else {
        search_wrapper.show();
        FA_progressIconLoader(search_wrapper.find('.search-header'));
        
        $.get(FA_source(), {t: 'search', a: 'header', q: query}, function (data) {
            
            if (data.status == 200) {
                
                if (data.html.length == 0) {
                    search_wrapper
                    .find('.search-list-wrapper')
                        .html('<div class="no-wrapper"><?php echo $lang['no_result_found']; ?></div>')
                    .end().find('a.page-link')
                            .hide();
                } else {
                    search_wrapper
                        .find('.search-list-wrapper')
                            .html(data.html)
                        .end()
                        .find('a.page-link')
                            .attr('href', data.link).show();
                }
            }
            
            FA_progressIconLoader(search_wrapper.find('.search-header'));
        });
    }
}
function FA_moreToggle() {
    $('.dropdown-search-container').hide();
    $('.dropdown-notification-container').hide();
    $('.notification-nav').removeClass('header-nav-active');
    $('.dropdown-more-container').toggle();
}
</script>