<?php
$available = false;

if (FA_getPostType($sk['post']['id']) == "story") {
    $sk['story'] = FA_getStory($sk['post']['id'], true);

    if (is_array($sk['story'])) {
        $available = true;
        
    }
}
?>
<div class="page-margin"></div>
<div class="float-left span63">
    <?php
    if ($available == true) {
        echo FA_getPage('story/content');
    } else {
    ?>
    <div class="empty-wrapper">
        <?php echo $lang['post_not_exist']; ?>
    </div>
    <?php
    }
    ?>
</div>
<?php
if ($sk['logged'] == true) {
?>
<div class="float-right span35">
    <div class="list-wrapper suggestions-wrapper">
        <div class="list-header">
            <div class="float-left">
                <?php
                echo $lang['follow_suggestions_label'];
                ?>
            </div>
            <div class="float-right">
                <span class="cursor-hand" onclick="refreshFollowSuggestions();" title="Refresh">
                    <i class="icon-repeat progress-icon"></i> 
                    <?php echo $lang['refresh_label']; ?>
                </span>
            </div>
            <div class="float-clear"></div>
        </div>
        <div class="suggestions-content">
            <?php
            foreach (FA_getFollowSuggestions() as $sk['suggestion']) {
                echo FA_getPage('home/suggestion-wrap');
            }
            ?>
        </div>
    </div>
    
    <div class="list-wrapper trending-wrapper">
        <div class="list-header">
            <?php echo $lang['trending_header_label']; ?>
        </div>
        <div class="trending-content">
            <?php
            $trendings = FA_getTrendings('popular');
            
            if (is_array($trendings) && count($trendings) > 0) {
                
                foreach ($trendings as $sk['trend']) {
                    echo FA_getPage('hashtag/trend-wrap');
                }
            }
            ?>
        </div>
    </div>
</div>
<?php
}
?>
<div class="float-clear"></div>

<?php
if ($sk['logged'] == true) {
?>
<script>
$(function () {
    $('.comments-container').slideDown();
});

function refreshFollowSuggestions() {
    
    FA_progressIconLoader($('.suggestions-wrapper').find('.list-header'));
    
    $.get(FA_source(), {t: 'search', a: 'suggestions'}, function (data) {
        
        if (data.status == 200) {
            $('.suggestions-content').html(data.html);
        }
        
        FA_progressIconLoader($('.suggestions-wrapper'));
    });
}
</script>
<?php
}
?>