<div id="message_recipient_<?php echo $sk['recipient']['id']; ?>" class="recipient-list cursor-hand" onclick="SK_getMessages(<?php echo $sk['recipient']['id']; ?>,'<?php echo $sk['recipient']['name']; ?>');">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
        <tr>
        <td width="32px" align="left" valign="middle">
            <img width="32px" height="32px" class="recipient-avatar" src="<?php echo $sk['recipient']['thumbnail_url']; ?>" alt="<?php echo $sk['recipient']['name']; ?>" valign="middle">
        </td>
        <td align="left" valign="middle">
            <span class="bold-500"><?php echo $sk['recipient']['name']; ?></span>
            <i class="icon-circle online-icon <?php if ($sk['recipient']['online'] == true) echo 'active'; ?>"></i>
            <?php
            $message_count = SK_countMessages(
                array(
                    'new' => true,
                    'recipient_id' => $sk['recipient']['id']
                )
            ); ?>
            <span class="update-alert <?php if ($message_count==0) echo 'hidden'; ?>"><?php echo $message_count; ?></span>
        </td>
        </tr>
    </table>
</div>