<div class="list-column suggestion-<?php echo $sk['suggestion']['id']; ?>">
    <table border="0" width="100%" cellspacing="0" cellpadding="0">
    <tr>
        <td width="42px" align="left" valign="middle">
            <a href="<?php echo $sk['suggestion']['url']; ?>" data-href="?tab1=timeline&id=<?php echo $sk['suggestion']['username']; ?>">
                <img width="36px" height="36px" class="radius3" src="<?php echo $sk['suggestion']['thumbnail_url']; ?>" alt="<?php echo $sk['suggestion']['name']; ?>">
            </a>
        </td>
        <td width="45%" align="left" valign="middle">
            <a class="bold-500" href="<?php echo $sk['suggestion']['url']; ?>" data-href="?tab1=timeline&id=<?php echo $sk['suggestion']['username']; ?>">
                <?php
                echo $sk['suggestion']['name'];
                ?>
            </a>
            <div class="info">
            <?php
            if ($sk['suggestion']['type'] == "user") {
                
                if (!empty($sk['suggestion']['current_city'])) {
                    echo $sk['suggestion']['current_city'];
                }
            } elseif ($sk['suggestion']['type'] == "page") {
                $category = FA_getPageCategoryData($sk['suggestion']['category_id']);
                echo $category['name'];
            } elseif ($sk['suggestion']['type'] == "group") {
                echo ucwords($sk['suggestion']['group_privacy']) . ' Group';
            }
            ?>
            </div>
        </td>
        <td class="column-btn" align="right" valign="middle">
            <?php
            echo FA_getFollowButton($sk['suggestion']['id']);
            ?>
        </td>
    </tr>
    </table>
</div>