<div class="page-margin"></div>

<div class="float-left span59">
    <form class="create-group-form" method="post">
        <div class="form-container">
            <div class="form-header"><?php echo $lang['group_create_label']; ?></div>
            <div class="form-input-wrapper">
                <label class="float-left span20"><?php echo $lang['group_name_label']; ?>:</label>
                
                <div class="input float-left span70">
                    <input type="text" value="<?php echo $lang['group_name_textarea_label']; ?>" placeholder="<?php echo $lang['group_name_textarea_label']; ?>" data-placeholder="<?php echo $lang['group_name_textarea_label']; ?>" onkeyup="SK_generateUsername(this.value);" data-copy-to=".group-name-input">
                    
                    <input class="group-name-input" type="hidden" name="group_name">
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20"><?php echo $lang['username_label']; ?>:</label>
                
                <div class="input float-left span70">
                    <input class="username-textinput" type="text" value="<?php echo $lang['group_username_textarea_label']; ?>" placeholder="<?php echo $lang['group_username_textarea_label']; ?>" data-placeholder="<?php echo $lang['group_username_textarea_label']; ?>" autocomplete="off" data-copy-to=".group-username-input" onkeyup="SK_checkUsername(this.value,0,'.check-username-result',true);">
                    
                    <input class="group-username-input" type="hidden" name="group_username">
                    
                    <div class="check-username-result"></div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    <?php
                    echo $lang['about_label'];
                    ?>:
                </label>
                
                <div class="input float-left span70">
                    <textarea class="auto-grow-input" valign="top" name="group_about" placeholder="<?php echo $lang['group_description_textarea_label']; ?>" data-placeholder="<?php echo $lang['group_description_textarea_label']; ?>"><?php echo $lang['group_description_textarea_label']; ?></textarea>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <label class="float-left span20">
                    <?php echo $lang['privacy_label']; ?>:
                </label>
                
                <div class="input float-left span70">
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="open">
                        <label><i class="icon-globe"></i> <?php echo $lang['open_group']; ?></label>
                        <div class="short-descr">
                            <?php echo $lang['open_group_description']; ?>.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 15px;">
                        <input valign="top" type="radio" name="group_privacy" value="closed" checked>
                        <label><i class="icon-lock"></i> <?php echo $lang['closed_group']; ?></label>
                        <div class="short-descr">
                            <?php
                            echo $lang['closed_group_description'];
                            ?>.
                        </div>
                    </div>
                    
                    <div style="margin-bottom: 10px;">
                        <input valign="top" type="radio" name="group_privacy" value="secret">
                        <label><i class="icon-shield"></i> <?php echo $lang['secret_group']; ?></label>
                        <div class="short-descr">
                            <?php
                            echo $lang['secret_group_description'];
                            ?>.
                        </div>
                    </div>
                </div>
                
                <div class="float-clear"></div>
            </div>
            
            <div class="form-input-wrapper">
                <button class="active">
                    <?php
                    echo $lang['group_create_label'];
                    ?>
                </button>
            </div>
        </div>
    </form>
</div>

<div class="float-right span40">
    <div class="list-wrapper">
        <div class="list-header"><?php echo $lang['group_intro_header']; ?></div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list1_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list1_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list2_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list2_description']; ?>
        </div>
        
        <div class="list-column">
            <strong class="bold-500"><?php echo $lang['group_intro_list3_header']; ?></strong>
            <br>
            <?php echo $lang['group_intro_list3_description']; ?>
        </div>
    </div>
</div>
<div class="float-clear"></div>
<script>
$(function () {
    $('form.create-group-form').ajaxForm({
        url: SK_source() + '?t=group&a=create',
        
        beforeSend: function() {
            $('form.create-group-form')
                .find('button')
                    .removeClass()
                    .text('<?php echo $lang['creating']; ?>...');
        },
        
        success: function(responseText) {
            
            if (responseText.status == 200) {
                window.location = responseText.url;
            }
            else {
                $('form.create-group-form')
                .find('button')
                    .addClass('active')
                    .text('<?php echo $lang['group_create_label']; ?>');
            }
        }
    });
});
</script>