<div class="window-container">
    <div class="window-background" onclick="FA_closeWindow();"></div>
    <div class="window-wrapper">
        <div class="window-header-wrapper">
            <i class="icon-minus-sign"></i> 
            Delete album?
            <span class="window-close-btn" title="Close window" onclick="FA_closeWindow();">
                <i class="icon-remove"></i>
            </span>
        </div>
        <div class="button-content-wrapper">
            <button onclick="FA_closeWindow();">
                <?php echo $lang['cancel']; ?>
            </button> 

            <button class="active" onclick="FA_deleteAlbum(<?php echo $sk['album']['id']; ?>);">
                <?php echo $lang['delete_button']; ?>
            </button>
        </div>
    </div>
</div>